#!/bin/bash

# get build configuration
source env.cnf
# get local workdir path
WORKDIR=${PWD}

# run container
#docker run -it -p ${PORT}:${PORT} -p 6006:6006 -v ${WORKDIR}/notebooks:${ROOT}/notebooks \
#           --gpus all --env-file ${WORKDIR}/env.cnf \
#           --name $CONTAINER_NAME --rm $CONTAINER_NAME

# run in the background
docker run -it -d -p ${PORT}:${PORT} -p 6006:6006 -v ${WORKDIR}/notebooks:${ROOT}/notebooks \
           --gpus all --env-file ${WORKDIR}/env.cnf \
           --name $CONTAINER_NAME --restart unless-stopped $CONTAINER_NAME

